### ISSUE TITLE
Divers: Bienvenue Jeff

### ISSUE THREAD

**Issue by Nemesis24** [Nemesis24/Personnal-issues#2]
Bienvenue à toi dans cette folle aventure, ensemble nous dompterons le Z !!!

Les devices , sous nos éclairs de javascript !!!  trembleront 
Les interrupteurs , à dos d'ajax !!! switcheront
Le waf , à coup de css !!! se soumetttra

Jeff 1er Maître Testeur tu seras !!!

**Comment by Jeffodilo** [comment]
C'est avec honneur que je relève le défi !
