### ISSUE TITLE
PUBLIC:(erreur) information lunaire

### ISSUE THREAD

**Issue by Jeffodilo** [Nemesis24/Personnal-issues#35]
Pensez a renommer l'icone ou le code pour l'icone "Sun"
GET http://192.168.1.30:8080/monitorz/icons/meteo/day/sun.png 404 (Not Found)

**Comment by Nemesis24** [comment]
Oui merci bien, tu m'avais déjà fait remarquer la chose, mais il semblerait que chrome, corrige par lui même la casse(interressant), cette erreur était bien réelle mais ne parraissait pas chez moi, Le code est donc changé car la casse est fourni par Forecast depuis domoticz.
