### ISSUE TITLE
Public : (amélioration) Trier device en ordre alphabétique

### ISSUE THREAD

**Issue by Jeffodilo** [Nemesis24/Personnal-issues#81]
Trier les devices en ordre alphabétique pour ne pas aller chercher dans Dz l'IDX du device

**Comment by Nemesis24** [comment]
j'utilise déjà la commande mais elle ne fonctionne pas dans domoticz

> /json.htm?type=devices&filter=all&used=true&order=Name

**Comment by Nemesis24** [comment]
finalement j'ai trouvé
